"""add_grading_fields_to_submission

Revision ID: d91ca570b7d8
Revises: 1778070f9adb
Create Date: 2026-03-13 18:19:15.287859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91ca570b7d8'
down_revision: Union[str, Sequence[str], None] = '1778070f9adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('submissions', sa.Column('grade', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('is_graded', sa.Boolean(), nullable=False, server_default='0'))
    
    # 为现有的已提交记录设置默认值
    # 已提交未评分记录默认 score=85.0、is_graded=false
    op.execute("""
        UPDATE submissions 
        SET score = 85.0, is_graded = 0 
        WHERE score IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'is_graded')
    op.drop_column('submissions', 'grade')
    op.drop_column('submissions', 'score')
    # ### end Alembic commands ###
